#!/bin/bash

folder="$(mktemp -d)"
branch=$(git rev-parse --abbrev-ref HEAD)

for file in $(ag -g ""); do
    mkdir -p "$folder/source/$(dirname "$file")"
    cp "$file" "$folder/source/$file"
done

pushd $folder
zip -r source.zip source/
aws s3 cp source.zip s3://codeperfect-private/source/$branch.zip
popd

rm -rf "$folder"
