#!/bin/bash
set -e

if [[ "$RELEASE" == "1" ]]; then
    sh/make clean
    ARCH=arm sh/make
    mv build/bin/ide build/ide-arm

    sh/make clean
    ARCH=x64 sh/make
    mv build/bin/ide build/ide-x64

	lipo -create -output build/bin/ide build/ide-arm build/ide-x64
    rm build/ide-arm
    rm build/ide-x64

    sh/make build/launcher
else
    sh/make prep
    sh/make
fi

if [[ ! -d ./build/bin/nvim/ ]]; then
    cp -R nvim-archive/ ./build/bin/nvim/

    # wipe out the share folder but keep clipboard handler
    rm -rf ./build/bin/nvim/share
    mkdir -p ./build/bin/nvim/share/nvim/runtime/autoload/provider
    cp nvim-archive/share/nvim/runtime/autoload/provider/clipboard.vim ./build/bin/nvim/share/nvim/runtime/autoload/provider
fi
