#!/bin/bash
set -e

# os="$(sh/detect_os)"
# if [[ $os = "windows" ]]; then
#     if [[ ! -z "$(tasklist /FI "IMAGENAME eq remedybg.exe" | grep remedybg)" ]]; then
#         remedybg stop-debugging
#     fi
# fi

if [[ "$RELEASE" == "1" ]]; then
    sh/make clean
    sh/make
    sh/make launcher
else
    sh/make prep
    sh/make
fi

if [[ ! -d ./build/bin/nvim/ ]]; then
    cp -R nvim-archive/ ./build/bin/nvim/

    # wipe out the share folder but keep clipboard handler
    rm -rf ./build/bin/nvim/share
    mkdir -p ./build/bin/nvim/share/nvim/runtime/autoload/provider
    cp nvim-archive/share/nvim/runtime/autoload/provider/clipboard.vim ./build/bin/nvim/share/nvim/runtime/autoload/provider
fi
