#!/bin/bash

# on windows, ensure visual studio is finished installing first

set -e

os=$(sh/detect_os)

# download submodules
git submodule update --init --recursive

if [[ "$os" = "linux" ]]; then
    sudo apt update
    sudo apt upgrade
    sudo apt install autoconf bison clang cloc cmake coreutils curl gcc git make neovim perl pkg-config python3 python-is-python3 silversearcher-ag tmux tree wget xclip
    sudo apt install libx11-dev libxft-dev autoconf libtool bison gperf libgles2-mesa-dev libxext-dev libxrandr-dev libxi-dev libxcursor-dev libxdamage-dev libxinerama-dev
    sudo apt install libgl1-mesa-dev libglu1-mesa-dev
    sudo apt install libgtk-3-dev
elif [[ $os = mac ]]; then
    if [[ -n $APP_CONNECT_PASSWORD ]]; then
        if [[ -n "$(which xcrun)" ]]; then
            xcrun notarytool store-credentials AC_PASSWORD --apple-id bh.apple@codeperfect95.com --team-id XCW98WVBHN --password $APP_CONNECT_PASSWORD
        else
            echo "xcrun not found, please install xcode-tools"
        fi
    else
        echo "please set APP_CONNECT_PASSWORD, it's in 1password"
    fi
fi

# vcpkg

if [[ $os = windows ]]; then
    cmd /c "vcpkg\bootstrap-vcpkg.bat -disableMetrics"
else
    ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
fi

if [[ "$os" = "windows" ]]; then
    vcpkg_binary=vcpkg/vcpkg.exe
else
    vcpkg_binary=vcpkg/vcpkg
fi

export VCPKG_DEFAULT_TRIPLET=$(sh/vcpkg_triplet)
$vcpkg_binary install --x-install-root=vcpkg/installed

# nvim
rm -rf nvim-archive
if [[ "$os" = "mac" ]]; then
    wget https://github.com/neovim/neovim/releases/download/v0.5.1/nvim-macos.tar.gz
    tar xvzf nvim-macos.tar.gz
    mv nvim-osx64 nvim-archive
    rm nvim-macos.tar.gz
elif [[ "$os" = "linux" ]]; then
    wget https://github.com/neovim/neovim/releases/download/v0.5.1/nvim-linux64.tar.gz
    tar xvzf nvim-linux64.tar.gz
    mv nvim-linux64 nvim-archive
    rm nvim-linux64.tar.gz
elif [[ "$os" = "windows" ]]; then
    wget https://github.com/neovim/neovim/releases/download/v0.5.1/nvim-win64.zip
    unzip nvim-win64.zip
    mv Neovim nvim-archive
    rm nvim-win64.zip

    # https://blog.yimingliu.com/2007/02/23/cvs-cygwin-and-error-code-0xc0000022/
    # On Windows in Cygwin, we get 0xc0000022 if we don't do this.
    find nvim-archive -type f \( -name '*.dll' -or -name '*.exe' \) | xargs chmod +x
fi

# wipe out the share folder but keep clipboard handler
mv nvim-archive/share/nvim/runtime/autoload/provider/clipboard.vim clipboard.vim
rm -rf nvim-archive/share
mkdir -p nvim-archive/share/nvim/runtime/autoload/provider
mv clipboard.vim nvim-archive/share/nvim/runtime/autoload/provider

# appify
go install github.com/machinebox/appify@latest
