#!/bin/bash

set -e

runtests() {
    echo $1
    if [[ $HEADLESS = "1" ]]; then
        build/bin/ide --jblow-tests $1 --headless
    else
        build/bin/ide --jblow-tests $1
    fi
}

runtests "vimfuzzer"
runtests "workspace"