#!/bin/bash

set -e

brew install glew pcre go coreutils cmake pkg-config xxhash

# install glfw using our custom formula which links statically
brew reinstall --build-from-source ./sh/glfw.rb

TMPDIR="/tmp/cwalk-for-cp"
rm -rf "$TMPDIR"
git clone https://github.com/likle/cwalk "$TMPDIR"
mkdir -p "$TMPDIR/build"
cd "$TMPDIR/build"
cmake ..
make
sudo make install
cd /tmp
rm -rf "$TMPDIR"

git submodule update --init --recursive
