#!/bin/bash

set -e

cmd="make"
nprocs=4

export MACOSX_DEPLOYMENT_TARGET=10.12
nprocs=$(sysctl hw.ncpu | grep -o '[0-9]\+')
if [ "$(sh/detect_m1)" = "1" ]; then
    cmd="arch -arm64 $cmd"
fi

$cmd -j $nprocs $@
