#!/bin/bash
set -e

VERSION="$(grep CurrentVersion gostuff/versions/versions.go | rev | cut -d' ' -f 1 | rev)"

# clear out everything for a fresh build
sh/make clean

# build again
RELEASE=1 sh/build_macos

OS_PREFIX=darwin
if [[ "$(sysctl -n machdep.cpu.brand_string)" = "Apple M1" ]]; then
    OS_PREFIX=darwin_arm
fi

package_app() {
    APPNAME="CodePerfect.app"
    rm -rf "${APPNAME}"
    mkdir -p "${APPNAME}/Contents/MacOS"
    cp -R ../build/bin/ "${APPNAME}/Contents/MacOS/bin/"
    cp ../build/launcher "${APPNAME}/Contents/MacOS/CodePerfect"
    zip -r app.zip CodePerfect.app/
    if [[ -z "$SKIP_UPLOAD" ]]; then
        aws s3 cp app.zip "s3://codeperfect95/app/${OS_PREFIX}_v${VERSION}.zip"
    fi
}

package_update() {
    zip -r update.zip ../build/bin/
    if [[ -z "$SKIP_UPLOAD" ]]; then
        aws s3 cp update.zip "s3://codeperfect95/update/${OS_PREFIX}_v${VERSION}.zip"
    fi
}

rm -rf scratch/
mkdir scratch/
cd scratch

package_app
package_update

sha256sum app.zip
sha256sum update.zip
