#!/bin/bash
set -e

VERSION="$(grep CurrentVersion gostuff/versions/versions.go | rev | cut -d' ' -f 1 | rev)"

# clear out everything for a fresh build
sh/make clean

# build again
RELEASE=1 sh/build_macos

OS_SLUG=darwin
if [[ "$(sysctl -n machdep.cpu.brand_string)" = "Apple M1" ]]; then
    OS_SLUG=darwin_arm
fi

package_app() {
    rm -rf CodePerfect.app

    appify -name CodePerfect \
        -icon ../logo.png \
        -version "0.${VERSION}.0" \
        -author "CodePerfect" \
        -id com.codeperfect95 \
        ../build/launcher

    rm -f CodePerfect.app/Contents/README
    rm -f CodePerfect.app/Contents/MacOS/bin/ide.d

    cp -R ../build/bin/ "CodePerfect.app/Contents/MacOS/bin/"

    zip -r app.zip CodePerfect.app/

    if [[ -z "$SKIP_UPLOAD" ]]; then
        aws s3 cp app.zip "s3://codeperfect95/app/${OS_SLUG}_v${VERSION}.zip"
    fi
}

package_update() {
    pushd ../build/bin
    zip -r ../../scratch/update.zip *
    popd

    if [[ -z "$SKIP_UPLOAD" ]]; then
        aws s3 cp update.zip "s3://codeperfect95/update/${OS_SLUG}_v${VERSION}.zip"
    fi
}

rm -rf scratch/
mkdir scratch/
cd scratch

package_app
package_update

APP_HASH="$(sha256sum app.zip)"
UPDATE_HASH="$(sha256sum update.zip)"

pushd ../gostuff
POSTGRES_URL=$POSTGRES_URL_PROD
go run ./cmd/addversion "$VERSION" "$OS_SLUG" "$APP_HASH" "$UPDATE_HASH"
popd
