#!/bin/bash
set -e

# grab version
pushd go
version_arr=($(go run ./cmd/printversion))
version=${version_arr[0]}
version_string=${version_arr[1]}
popd

slug=x64

# build the actual app
if [[ -z "$NO_REBUILD" ]]; then
    RELEASE=1 sh/build
fi

# create scratch directory
rm -rf scratch/
mkdir scratch/
cd scratch

if [[ "$(../sh/detect_m1)" = "1" ]]; then
    slug=arm
fi

# create .app from ide
rm -rf CodePerfect.app
appify -name CodePerfect \
    -icon ../web/public/logo.png \
    -version $version_string \
    -author "CodePerfect" \
    -id com.codeperfect95 \
    ../build/bin/ide
rm ../build/bin/ide
rm -rf ../build/bin/ide.dSYM
cp ../build/bin/* "CodePerfect.app/Contents/MacOS"
rm -rf CodePerfect.app/Contents/README

# zip up app
ditto -c -k --keepParent CodePerfect.app "mac-$slug-$version_string.zip"
