#!/bin/bash
version=$1

if [[ -z $version ]]; then
    pushd go
    version=$(go run ./cmd/printversion | cut -d' ' -f1)
    popd
fi

echo "updating with version $version"

echo "{\"current_version\": $version}" > /tmp/meta.json
aws s3 cp /tmp/meta.json s3://codeperfect95/meta.json
rm /tmp/meta.json
