#!/bin/bash

set -e

# download submodules
git submodule update --init --recursive

# apt-cyg must be installed
apt-cyg install binutils make  # there's more but i forgot to record

# vcpkg must be installed
export VCPKG_DEFAULT_TRIPLET=x64-windows-static
vcpkg install pcre harfbuzz fontconfig
vcpkg integrate install

# nvim
wget https://github.com/neovim/neovim/releases/download/v0.5.1/nvim-win64.zip
unzip nvim-win64.zip
mv Neovim nvim-archive
rm nvim-win64.zip

# wipe out the share folder but keep clipboard handler
mv nvim-archive/share/nvim/runtime/autoload/provider/clipboard.vim clipboard.vim
rm -rf nvim-archive/share
mkdir -p nvim-archive/share/nvim/runtime/autoload/provider
mv clipboard.vim nvim-archive/share/nvim/runtime/autoload/provider

# appify
go install github.com/machinebox/appify@latest
