# Meta Data for SEO

## Homepage
title = "CodePerfect 95"
titleSeparator = "-"
titleAddition = "A Fast IDE for Go"
description = "CodePerfect 95 is a fast IDE for Go."

## Sitelinks Search Box
siteLinksSearchBox = false

# Footer
footer = "&copy; CodePerfect 95"
copyRight = "&copy; CodePerfect 95"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = false
  breadCrumb = true
  highLight = true
  collapsibleSidebar = false
