name: Deploy

on:
  push:
    branches:
    - master

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Deploy
      run: sh/deploy/run_helper sh/deploy/checkout

  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Deploy
      run: |
        sh/deploy/run_helper sh/deploy/api
